---
version: 2
multicolumn: false
web-width: 500
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/HX-property/HX.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/227193/articles/308389/master/folder/figures/HX-property"
    url: "/users/227193/articles/308389/master/file/figures/HX-property/HX.png"
