---
version: 2
multicolumn: false
web-width: 500
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/6D__Dropbox_Granty__UNICORN__Zadania_Zadanie_3_____Vernon_-_sCO2_Brayton_operation___analysis/6D__Dropbox_Granty__UNICORN__Zadania_Zadanie_3_____Vernon_-_sCO2_Brayton_operation___analysis.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/227193/articles/308389/master/file/figures/6D__Dropbox_Granty__UNICORN__Zadania_Zadanie_3_____Vernon_-_sCO2_Brayton_operation___analysis/6D__Dropbox_Granty__UNICORN__Zadania_Zadanie_3_____Vernon_-_sCO2_Brayton_operation___analysis.png"
    folder_url: "/users/227193/articles/308389/master/folder/figures/6D__Dropbox_Granty__UNICORN__Zadania_Zadanie_3_____Vernon_-_sCO2_Brayton_operation___analysis"
