---
version: 2
multicolumn: false
web-width: 500
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/10D__Dropbox_Granty__UNICORN__Zadania_Zadanie_3___zadzen_Pictures_MainCompressorTurbineCurves/10D__Dropbox_Granty__UNICORN__Zadania_Zadanie_3___zadzen_Pictures_MainCompressorTurbineCurves.svg
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/227193/articles/308389/master/file/figures/10D__Dropbox_Granty__UNICORN__Zadania_Zadanie_3___zadzen_Pictures_MainCompressorTurbineCurves/10D__Dropbox_Granty__UNICORN__Zadania_Zadanie_3___zadzen_Pictures_MainCompressorTurbineCurves.svg"
    folder_url: "/users/227193/articles/308389/master/folder/figures/10D__Dropbox_Granty__UNICORN__Zadania_Zadanie_3___zadzen_Pictures_MainCompressorTurbineCurves"
