---
version: 2
multicolumn: false
web-width: 200
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/7D__Dropbox_Granty__UNICORN__Zadania_Zadanie_3_Modele_urzadzen_Pictures_CompressorModel/7D__Dropbox_Granty__UNICORN__Zadania_Zadanie_3_Modele_urzadzen_Pictures_CompressorModel.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/227193/articles/308389/master/file/figures/7D__Dropbox_Granty__UNICORN__Zadania_Zadanie_3_Modele_urzadzen_Pictures_CompressorModel/7D__Dropbox_Granty__UNICORN__Zadania_Zadanie_3_Modele_urzadzen_Pictures_CompressorModel.png"
    folder_url: "/users/227193/articles/308389/master/folder/figures/7D__Dropbox_Granty__UNICORN__Zadania_Zadanie_3_Modele_urzadzen_Pictures_CompressorModel"
